#!/usr/bin/env node
"use strict";

// Runs before `npm pack`/`npm publish` (via the "prepack" script in package.json).
// .npmignore is NOT consulted when package.json's "files" field is set, so
// Python bytecode caches generated by running doctor.py/pytest locally would
// otherwise leak into the published tarball. Deletes them instead.

const fs = require("fs");
const path = require("path");

function removePycache(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "__pycache__" || entry.name === ".pytest_cache") {
        fs.rmSync(abs, { recursive: true, force: true });
      } else {
        removePycache(abs);
      }
    } else if (abs.endsWith(".pyc") || abs.endsWith(".pyo")) {
      fs.rmSync(abs, { force: true });
    }
  }
}

removePycache(path.join(__dirname, "..", ".agent"));
